# Generated by Django 6.0 on 2026-03-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('Python', 'Python'), ('PHP', 'PHP'), ('Laravel', 'Laravel'), ('Django', 'Django'), ('Java', 'Java'), ('JavaScript', 'JavaScript')], default='Python', max_length=20),
        ),
    ]
