# Generated by Django 6.0 on 2026-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
